site_name: Run:ai
theme:
  name: material
extra:
  version:
    provider: mike

plugins:
  - mike:
      # # These fields are all optional; the defaults are as below...
      # alias_type: symlink
      # redirect_template: null
      # deploy_prefix: ''
      # canonical_version: null
      version_selector: true